# version: "3"
# services:
#   db:
#     image: postgres:latest
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: physifix_db
#       POSTGRES_USER: postgresql
#       POSTGRES_PASSWORD: postgresql
